language: python
python:
  - "3.6"
  - "3.7-dev"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
dist: bionic
sudo: true
install:
  - "pip install flake8 pycodestyle"
  - "pip install -r requirements.txt"
script:
  - "pycodestyle xjs"
  - "flake8 xjs"
  - python3 xjs examples/example1.json > /dev/null
  - python3 xjs --offline examples/example2.json > /dev/null
  - python3 xjs --offline examples/example3.yaml > /dev/null
  - python3 xjs --offline examples/example4.yaml > /dev/null
  - python3 xjs --offline examples/example5.json examples/example6.json > /dev/null
  - python3 xjs --offline --application openstack-dashboard examples/example1.json > /dev/null
  - python3 xjs --offline --application filebeat examples/example1.json > /dev/null
  - python3 xjs --offline --model k8s-tigera examples/example5.json examples/example6.json > /dev/null
  - python3 xjs --offline --controller nniehoff examples/example5.json examples/example6.json > /dev/null
  - python3 xjs --offline --unit kubernetes-master/0 examples/example5.json examples/example6.json > /dev/null
  - python3 xjs --offline --subordinate flannel/2 examples/example5.json examples/example6.json > /dev/null
