language: python
python:
  - "3.6"
  - "3.7-dev"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
dist: bionic
sudo: true
install:
  - "pip install -r requirements.txt"
script:
  - "pycodestyle xjs"
  - "flake8 xjs"
  - python3 xjs examples/example1.json > /dev/null
  - python3 xjs examples/example2.json > /dev/null
  - python3 xjs examples/example3.yaml > /dev/null
  - python3 xjs examples/example4.yaml > /dev/null
  - python3 xjs examples/example5.json examples/example6.json > /dev/null