name: xjs
base: core18
version: 'git'
summary: A tool to parse juju status yaml/json
architectures:
  - amd64
description: |
  XJS Provides a way to parse complex juju status yaml/json files in a simple
  way.

license: GPL-3.0

confinement: strict

parts:
  xjs:
    source: .
    plugin: python
    python-version: python3
    python-packages:
      - pyyaml
      - prettytable
      - click
      - packaging
      - requests
      - pendulum

apps:
  xjs:
    command: xjs
    plugs:
     - home
     - network
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8


