name: xjs
base: core18
version: 'git'
summary: A tool to parse juju status yaml/json
architectures:
  - amd64
description: |
  XJS Provides a way to parse complex juju status yaml/json files in a simple
  way.

license: GPL-3.0

confinement: classic

parts:
  xjs:
    override-prime: |
      snapcraftctl prime
      cd bin
      _XJS_COMPLETE=source ./xjs > ../xjs.bash-completion || echo "Built Bash Completion"
    source: .
    plugin: python
    python-version: python3
    requirements: [ ./requirements.txt ]

apps:
  xjs:
    command: xjs
    plugs:
     - home
     - network
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
